name: Release Bot

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., v0.24.0)"
        required: true

jobs:
  note:
    name: README.md
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git tag
      - run: python3 tools/release/note_create.py
      - run: git diff
      - run: python3 tools/release/note_update.py
      - run: git diff
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update RELEASE.md [bot]
          branch: bot-RELEASE.md
          delete-branch: true
          title: 'Update RELEASE.md [bot]'
          body: |
            README.md: auto-updated by .github/workflows/release.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          set -x -e
          if [[ "$(git tag -l ${{ github.event.inputs.version }})" == "${{ github.event.inputs.version }}" ]]; then
            echo "${{ github.event.inputs.version }} already released"
            exit 1
          fi
          echo "::set-output name=version::${VERSION}"
        id: info
