name: Release Bot

on:
  push:
  #  branches:
  #    - master
  workflow_dispatch:
    inputs:
      version:
        description: "Version (e.g., v0.24.0)"
        required: true

jobs:
  note:
    name: README.md
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git tag
      - run: python3 tools/release/note_create.py
      - run: git diff
      - run: python3 tools/release/note_update.py
      - run: git diff
      - uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update RELEASE.md [bot]
          branch: bot-RELEASE.md
          delete-branch: true
          title: 'Update RELEASE.md [bot]'
          body: |
            README.md: auto-updated by .github/workflows/release.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          set -x -e
          echo "${{ github.event.inputs.version }} already released"
          VERSION=$(grep 'version = ' tensorflow_io/python/ops/version_ops.py  | sed -E 's@^.*version = "@@g' | sed -E 's@".*$@@g')
          echo "::set-output name=version::${VERSION}"
        id: info
      - uses: docker/login-action@v1
        with:
          username: tfsigio
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          set -x -e
          docker pull tfsigio/candidate:${{ steps.info.outputs.version }}
          docker images
